### ISSUE TITLE
tsconfig.json not found as of 7.6.x with custom typescriptServices.js

### ISSUE THREAD

**Issue by Sleeckx** [TypeStrong/atom-typescript#685]
After upgrading to 7.6.0 atom-typescript reports no tsconfig.json found.
I reverted to 7.5.1 at then it works again.

My project structure is as follow:

```
/
+-- tsconfig.json
+-- src/
¦   +-- demo.html
¦   +-- WebComponents/
¦   ¦   +-- ActionBar/
¦   ¦   ¦   +-- action-bar.html
¦   ¦   ¦   +-- action-bar.less
¦   ¦   ¦   +-- action-bar.ts
¦   ¦   +-- ActionButton/
¦   ¦   ¦   +-- action-button.html
¦   ¦   ¦   +-- action-button.less
¦   ¦   ¦   +-- action-button.ts
¦   ¦   +-- App/
¦   ¦   ¦   +-- app.html
¦   ¦   ¦   +-- app.less
¦   ¦   ¦   +-- app.ts
¦   ¦   +-- ...
```

tsconfig.json has the following content:

``` json
{
  "compilerOptions": {
    "target": "es5",
    "removeComments": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": false,
    "sourceMap": false
  },
  "filesGlob": [
    "src/Libs/**/*.ts",
    "src/WebComponents/**/*.ts"
  ],
  "files": [
    ...
  ],
  "exclude": [
    ...
  ]
}
```

**Comment by samu** [comment]
:+1: same problem here. Stopped working with latest release.

**Comment by samu** [comment]
resolved with `7.6.3`

Thanks, that was quick!

**Comment by Sleeckx** [comment]
Hmm, not here. I'm still getting "no tsconfig.json". Going back to 7.5.1 still fixes it for me so I don't think it's a local problem.

**Comment by daniel-a-melo** [comment]
If I configure the full path of `typescriptServices.js` it doesn't find the `tsconfig.json` file. If I leave the config empty (and therefore it will used the bundled `ntypescript` it does work correctly. 
atom-typescript version 7.6.3, atom 1.0.11

**Comment by Sleeckx** [comment]
Can confirm. Removing the custom path to ```typescriptServices.js``` also fixes it for my project.

**Comment by basarat** [comment]
I've renamed the title. If people not using `typescriptServices` also have the issue please concern (or create a new issue) :rose:

**Comment by basarat** [comment]
I've looked at the code. [Here we just delegate](https://github.com/TypeStrong/atom-typescript/blob/8a597435c100ad2f5000ed5280bd53375247a467/lib/main/tsconfig/tsconfig.ts#L360-L365)  to the [tsconfig `resolveSync` function](https://github.com/TypeStrong/tsconfig/blob/ea9f710a30bf364c86993abfbd7b92ee376e0b61/src/tsconfig.ts#L55-L68)

Can someone using typescriptService put a `console.error` our [code](https://github.com/TypeStrong/atom-typescript/blob/8a597435c100ad2f5000ed5280bd53375247a467/lib/main/tsconfig/tsconfig.ts#L360-L365) to see if this is indeed the case. I'll try eventually anyways. Up for grabs for now.
