### ISSUE TITLE
jsdoc tags and "todo"-type comments not being highlighted 

### ISSUE THREAD

**Issue by dsifford** [TypeStrong/atom-typescript#958]
Not sure if this issue should be filed here, with docblockr, or somewhere else, but in all my `.ts` and `.tsx` files, I'm not getting syntax highlighting for jsdoc tags and also I'm not getting highlighting for "todo"-type comments (for the most part -- see below).
#### jsdoc

Class methods:
![image](https://cloud.githubusercontent.com/assets/5240018/15374061/8bab0b98-1d16-11e6-9e8d-df228d8572e4.png)

Function definitions
![image](https://cloud.githubusercontent.com/assets/5240018/15374082/a51860c6-1d16-11e6-9d8c-9852c99bbb23.png)

...etc etc.
#### todos

Doesn't work at all in inline comments, but _does_ work for multiline-style..
![image](https://cloud.githubusercontent.com/assets/5240018/15374179/10552496-1d17-11e6-800c-216164a7cda8.png)

Thanks so much for your work on this package. 👍

**Comment by googol7** [comment]
see also: https://github.com/TypeStrong/atom-typescript/issues/848

**Comment by googol7** [comment]
Finally the "todo"-type comments have been resolved with release [v10.1.8](https://github.com/TypeStrong/atom-typescript/releases/tag/v10.1.8)

**Comment by Nxt3** [comment]
The `TODO` in inline comments is still broken for me as well, and I'm on version 11.0.1
